AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AwsNamespace:
    Type: String
    Description: Used to generate namespaced AWS resources

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AwsNamespace}-lambda-58d3c996-bc32-4636-8ece-b7b7b605066e
      AccessControl: AuthenticatedRead
