AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AwsNamespace:
    Type: String
    Description: Used to generate namespaced AWS resources

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AwsNamespace}-lambda-60b77a97-ed05-45e2-a19f-2f0d1ec7dd63
      AccessControl: AuthenticatedRead
